ignore-build:
  - docs/**
  - .github/CODEOWNERS
  - .gitignore
  - LICENSE
  - '*.md'
chisel:
  - runtime/tools/chisel/**
emitc:
  - test/ttmlir/EmitC/**
  - tools//ttnn-standalone/ci_compile_dylib.py
  - include/ttmlir/Conversion/TTNNToEmitC/**
  - lib/Conversion/TTNNToEmitC/**
