name: Build and Test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      metal_override:
        description: 'Git SHA of commit in tenstorrent/tt-metal'
        required: false
        type: string
      builder_build:
        description: 'Run build on builder'
        required: false
        type: boolean

permissions:
  checks: write
  packages: write

jobs:

  ignore-files:
    runs-on: ubuntu-latest
    outputs:
      other_changed_files: ${{ steps.ignore-files.outputs.other_changed_files }}
      other_deleted_files: ${{ steps.ignore-files.outputs.other_deleted_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ignore files
        id: ignore-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            docs/**
      - name: echo ignore_files
        run: |
          echo "any_changed=${{ steps.ignore-files.outputs.any_changed }}"
          echo "only_changed=${{ steps.ignore-files.outputs.only_changed }}"
          echo "other_changed_files=${{ steps.ignore-files.outputs.other_changed_files }}"
          echo "all_changed_files=${{ steps.ignore-files.outputs.all_changed_files }}"
          echo "other_deleted_files=${{ steps.ignore-files.outputs.other_deleted_files }}"

  build-image:
    needs: ignore-files
    if: ${{ needs.ignore-files.outputs.other_changed_files || needs.ignore-files.outputs.other_deleted_files }}
    runs-on:
      - builder
    outputs:
      docker-image-harbor: ${{ steps.build.outputs.docker-image-harbor }}
      docker-image: ${{ steps.build.outputs.docker-image }}
      docker-tag: ${{ steps.build.outputs.docker-tag }}
      runner: ${{ steps.build.outputs.runner }}
    steps:

      - name: Fix permissions
        shell: bash
        run: sudo chown ubuntu:ubuntu -R $(pwd) || true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images and output the image name
        id: build
        shell: bash
        run: |
          # Output the image name
          set pipefail
          .github/build-docker-images.sh | tee docker.log
          DOCKER_CI_IMAGE=$(tail -n 1 docker.log)
          DOCKER_TAG=$(.github/get-docker-tag.sh)
          echo "DOCKER_CI_IMAGE $DOCKER_CI_IMAGE"
          echo "DOCKER_TAG $DOCKER_TAG"
          echo "docker-image-harbor=harbor.ci.tenstorrent.net/$DOCKER_CI_IMAGE" >> "$GITHUB_OUTPUT"
          echo "docker-image=$DOCKER_CI_IMAGE" >> "$GITHUB_OUTPUT"
          echo "docker-tag=$DOCKER_TAG" >> "$GITHUB_OUTPUT"
          if [[ "${{ inputs.builder_build }}" == "true" ]]; then
            echo "runner=builder" >> "$GITHUB_OUTPUT"
          else
            echo "runner=ubuntu-latest" >> "$GITHUB_OUTPUT"
          fi

  build-ttmlir-wheel:
    needs:
      - build-image
    uses: ./.github/workflows/wheel-build.yml
    with:
      docker-tag: ${{ needs.build-image.outputs.docker-tag }}
