
name: Build on macos-latest

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: get reports
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      shell: bash
      id: rep
      run: |
        gh run download 18307092217 --repo tenstorrent/tt-mlir --name "test-reports-n150-tracy-52128249415"
        echo "# Test Report" > summary.md
        echo "Test 1: pytest.sh tools/explorer/test/run_tests.py" >> summary.md
        echo "Test 2: pytest.sh runtime/tools/chisel/test" >> summary.md
        echo "Test 3: builder.sh test/python/golden" >> summary.md
        echo "Test 4: ttrt.sh perf Silicon/TTNN/n150/optimizer" >> summary.md
        echo "Test 5: ttnn_runtime.sh runtime/test/ttnn/python/device_agnostic" >> summary.md
        echo "Test 6: emitc.sh" >> summary.md
        echo "summary=\"$(cat summary.md)\"" >> $GITHUB_OUTPUT
    - name: Show Test Report
      uses: mikepenz/action-junit-report@v5.6.2
      if: success() || failure()
      with:
        report_paths: report_*.xml
        check_name: "n150-tracy Tests"
        summary: '${{ steps.rep.outputs.summary }}'
